### ISSUE TITLE
Uknown Property Product::Product on adding to cart

### ISSUE THREAD

**Issue by 3dgroup** [nystudio107/craft3-instantanalytics#27] opened 2020-02-14 11:25 UTC
Get the following error when adding one of my product types to cart (other product types work):

GETTING UNKNOWN PROPERTY: CRAFT\COMMERCE\ELEMENTS\PRODUCT::PRODUCT

originating from :

in /app/vendor/nystudio107/craft-instantanalytics/src/services/Commerce.php at line 475– craft\base\Element::__get('product')

Seems if a specific product doesn't have the specific Commerce Product Category Field it throws this error.

**Comment by nerdymind-dev** [comment] 2020-03-13 20:57
Getting this exact same issue. Not sure what the cause is.

**Comment by khalwat** [comment] 2020-04-06 20:07
Fixed in https://github.com/nystudio107/craft-instantanalytics/commit/04a0e16205c52073ea427749326bd91dc765d911

**Closed as completed by khalwat** 2020-04-06 20:07 UTC
